apiVersion: 1

datasources:
  - name: InfluxDB-Gas
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: thesis-org
      defaultBucket: gas_sensor_data
      tlsSkipVerify: true
    secureJsonData:
      token: thesis-super-token
